This should go to logs
Object (fromList [("error",Number 1.0)])
{"errorType":"ErrorCall","errorMessage":"Magic error\nCallStack (from HasCallStack):\n  error, called at Main.hs:29:30 in main:Main"}
  Error --------------------------------------------------
<Serverless error omitted>
